/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabletrainer;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jackzz
 */
public class Trainer extends javax.swing.JFrame {

    private String[] availableLanguage = {"German", "English", "French", "Spanish"};
    private Configuration config = new Configuration();
    private ArrayList<Vocable> vocableList = new ArrayList<>();

    /**
     * Creates new form Main
     */
    public Trainer() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public Trainer(Configuration config) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.config = config;
        startTraining();
    }

    public void readFile() {
        String csvFile = config.getVocablePath();
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";

        try {

            br = new BufferedReader(
                    new InputStreamReader(new FileInputStream(csvFile), "UTF-8"));
            while ((line = br.readLine()) != null) {

                // use comma as separator
                String[] vocables = line.split(cvsSplitBy);
                Vocable newVocable = new Vocable(vocables[0], vocables[1]);
                vocableList.add(newVocable);

            }
            Collections.shuffle(vocableList);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public void startTraining() {
        if (config.isWrongVocables()) {
            vocableList = config.getWrongVocableList();
            config.clearVocableList();
            config.setWrongVocables(false);
        } else {
            readFile();
        }

        if (config.isNativeToLang()) {
            jLabelNative.setText("Native");
            jLabelLanguage.setText(config.getChosenLanguage());
        } else {
            jLabelNative.setText(config.getChosenLanguage());
            jLabelLanguage.setText("Native");
        }

        config.clearRight();
        nextVocable();
    }

    public void nextVocable() {
        if (vocableList.size() > 0) {
            if (config.isNativeToLang()) {
                jTextFieldNative.setText(vocableList.get(0).getNativeVocable());
            } else {
                jTextFieldNative.setText(vocableList.get(0).getChosenVocable());
            }
        } else {
            endTraining();
        }
    }

    public void endTraining() {
        new Result(config).setVisible(true);
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLanguage = new javax.swing.JLabel();
        jLabelNative = new javax.swing.JLabel();
        jTextFieldNative = new javax.swing.JTextField();
        jTextFieldLanguage = new javax.swing.JTextField();
        btnRight = new javax.swing.JButton();
        btnFalse = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 182, 42));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 138, 178));
        jLabel1.setText("Vocable Trainer");

        jLabelLanguage.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabelLanguage.setForeground(new java.awt.Color(251, 253, 253));
        jLabelLanguage.setText("Chosen:");

        jLabelNative.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabelNative.setForeground(new java.awt.Color(251, 253, 253));
        jLabelNative.setText("Language:");

        jTextFieldNative.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        jTextFieldNative.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNative.setFocusable(false);

        jTextFieldLanguage.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        jTextFieldLanguage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLanguage.setFocusable(false);

        btnRight.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        btnRight.setText("Right");
        btnRight.setEnabled(false);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnFalse.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        btnFalse.setText("False");
        btnFalse.setEnabled(false);
        btnFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFalseActionPerformed(evt);
            }
        });

        btnCheck.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNative)
                            .addComponent(jTextFieldLanguage))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabelLanguage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabelNative, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnHome))
                .addGap(31, 31, 31)
                .addComponent(jLabelNative)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNative, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRight, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFalse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        btnCheck.setEnabled(false);
        btnRight.setEnabled(true);
        btnFalse.setEnabled(true);

        if (vocableList.size() > 0) {
            if (config.isNativeToLang()) {
                jTextFieldLanguage.setText(vocableList.get(0).getChosenVocable());
            } else {
                jTextFieldLanguage.setText(vocableList.get(0).getNativeVocable());
            }
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        config.addRight();
        vocableList.remove(0);
        jTextFieldLanguage.setText("");
        nextVocable();

        btnCheck.setEnabled(true);
        btnRight.setEnabled(false);
        btnFalse.setEnabled(false);
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFalseActionPerformed
        // TODO add your handling code here:
        config.getWrongVocableList().add(vocableList.get(0));
        vocableList.remove(0);
        jTextFieldLanguage.setText("");
        nextVocable();

        btnCheck.setEnabled(true);
        btnRight.setEnabled(false);
        btnFalse.setEnabled(false);
    }//GEN-LAST:event_btnFalseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnFalse;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelNative;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldLanguage;
    private javax.swing.JTextField jTextFieldNative;
    // End of variables declaration//GEN-END:variables
}
